import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>facebook app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-3xl font-bold text-pink-200 underline">
          Hello world!
        </h1>
      </main>
    </div>
  );
}
